### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by ghost** [kw2019ltd/corova_virus_app#3]
Im getting Out of Memory Problems

Running Gradle task 'assembleDebug'...
c:\b\s\w\ir\cache\builder\src\third_party\dart\runtime\vm\zone.cc: 90: error: Out of memory.
version=2.7.2 (Mon Mar 23 22:11:27 2020 +0100) on "windows_x64"
thread=12996, isolate=main(000002514736FE10)
  pc 0x00007ff740554adb fp 0x0000005783afe640 Unknown symbol
-- End of DumpStackTrace

**Comment by kw2019ltd** [comment]
this is something from your you need to check you setting.
