### ISSUE TITLE
Please provide local.properties, I am unable to build on my local machine

### ISSUE THREAD

**Issue by aloksguha** [kw2019ltd/corova_virus_app#4]
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/alok.guha/dev/mines/flutter/corova_virus_app/android/app/build.gradle' line: 59

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by kw2019ltd** [comment]
hi local properties is being generated buy flutter build.. 

in .gitignore its already ignored.. 
**/android/local.properties

any way its something like 
sdk.dir=C:\\Users\\XXX\\AppData\\Local\\Android\\sdk
flutter.sdk=C:\\Tools\\flutter
flutter.buildMode=debug
flutter.versionName=1.0.0
flutter.versionCode=5
